[package]
name = "npmstats"
version = "0.1.0"
authors = ["Terence Lee <hone02@gmail.com>"]

[dependencies]
chrono = "0.4.0"
docopt = "0.8.1"
gnuplot = "0.0.22"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.7.3"
